name: PR-to-main
on:
    pull_request:
        branches:
            - main
jobs:
    PR-to-main:
        runs-on: ubuntu-latest
        timeout-minutes: 1

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.18.0

            - name: Retrieve cached dependencies
              id: cache-nodemodules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install dependencies
              if: steps.cache-nodemodules.outputs.cache-hit != 'true'
              run: npm ci

            - name: Check formatting
              run: npm run prettier-check
